version: 2.1
orbs:
  cypress: cypress-io/cypress@1.26.0
workflows:
  test:
    jobs:
      - cypress/run:
          start: npm start
          wait-on: 'http://localhost:9001'
          record: true
          