version: 2.1
orbs:
  cypress: cypress-io/cypress@1.26.0
# Orchestrate or schedule a set of jobs
workflows:
  test:
    # Run the welcome/run job in its own container
    jobs:
      - cypress/run:
          start: npm start
          wait-on: 'http://localhost:9001'
          record: true
          